---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edge
  labels:
    name: edge
    layer: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: edge
        layer: client
    spec:
      containers:
      - name: edge
        image: iad.ocir.io/oracle/ateam/mushop-edge-router:1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8081
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /ping
            port: http
        readinessProbe:
          httpGet:
            path: /ping
            port: http