---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storefront
  labels:
    name: storefront
    layer: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: storefront
        layer: client
    spec:
      containers:
      - name: storefront
        image: iad.ocir.io/oracle/ateam/mushop-storefront:2.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8081
        - name: status
          containerPort: 8888
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory